package zcslib.mixin;

import java.nio.file.Path;
import java.util.List;

/**
 * Parsed declaration from a plugin JAR's {@code zcslib.mixin.json}.
 *
 * <p>Each plugin that wants to contribute Mixin classes ships this file
 * at the JAR root, listing its Mixin classes and pointing to the standard
 * refmap generated by the Mixin annotation processor.
 *
 * @param pluginId     unique plugin identifier
 * @param refmap       absolute path to the plugin's refmap JSON inside the JAR
 * @param mixinClasses fully-qualified Mixin class names to register
 */
record PluginMixinDecl(String pluginId, Path refmap, List<String> mixinClasses) {}
