package zcslib.mixin;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import org.slf4j.Logger;
import com.mojang.logging.LogUtils;

import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashSet;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Rewrites a Mixin refmap JSON so that obfuscated names match the
 * <em>current</em> runtime version rather than the compile-time version.
 *
 * <h3>How it works</h3>
 * <ol>
 *   <li>Parse the plugin's refmap JSON (generated by the Mixin AP).</li>
 *   <li>Walk every mapping entry whose value is a <em>member reference</em>
 *       of the form {@code Lclass;member(desc)ret} or {@code Lclass;member:type}.</li>
 *   <li>Look up each class in the {@link MappingTable} to find the
 *       Mojang &harr; obf correspondence.</li>
 *   <li>If the member's obfuscated name differs in the current version,
 *       replace the reference with the updated obf name.</li>
 *   <li>Write the corrected refmap to a temp file under
 *       {@code plugins/refmaps/} for Mixin to consume.</li>
 * </ol>
 *
 * <p>Entries whose target class is not in the mapping table are kept unchanged
 * (logged at WARN level once per class). This handles the common case where
 * class names are stable across versions but method/field obf names change.
 */
public final class RefmapResolver {

    private static final Logger LOGGER = LogUtils.getLogger();
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
    private static final Gson PARSER = new Gson();

    /**
     * Regex for a Mixin member reference:
     * {@code L<fully/qualified/ClassName>;<memberName>(<descriptor>)<returnType>}
     * or {@code L<fully/qualified/ClassName>;<memberName>:<type>}
     *
     * <p>Group 1 = fully-qualified class name (with / separators)
     * <br>Group 2 = member name (method or field)
     * <br>Group 3 = descriptor suffix: {@code (desc)ret} for methods, {@code :type} for fields
     */
    private static final Pattern MEMBER_REF_PATTERN =
            Pattern.compile("^L([^;]+);([^(:\s]+)(\\([^)]*\\)[^\\s]*|:[^\\s]*)$");

    private final JsonObject root;
    private final MappingTable mappingTable;
    private final int originalEntryCount;
    private int rewrittenCount;

    /** Tracks classes already warned about (once per class per refmap). */
    private final Set<String> unmappedClasses = new HashSet<>();

    private RefmapResolver(JsonObject root, MappingTable mappingTable, int originalEntryCount) {
        this.root = root;
        this.mappingTable = mappingTable;
        this.originalEntryCount = originalEntryCount;
        this.rewrittenCount = 0;
    }

    // ── Public API ─────────────────────────────────────────

    /**
     * Parse a plugin refmap JSON and rewrite all obfuscated member references
     * to match the current runtime version's obfuscation scheme.
     *
     * @param refmapPath   path to the plugin's standard Mixin refmap JSON
     * @param mappingTable the version mapping table for the current runtime
     * @return a {@code RefmapResolver} holding the corrected refmap in memory
     * @throws IOException if the file cannot be read or parsed
     */
    public static RefmapResolver resolve(Path refmapPath, MappingTable mappingTable)
            throws IOException {
        LOGGER.debug("[ZCSLIB/Mixin] Resolving refmap: {}", refmapPath);

        JsonObject root;
        try (Reader reader = Files.newBufferedReader(refmapPath, StandardCharsets.UTF_8)) {
            root = PARSER.fromJson(reader, JsonObject.class);
        } catch (JsonParseException e) {
            throw new IOException("Malformed refmap JSON: " + refmapPath, e);
        }

        if (root == null) {
            throw new IOException("Empty refmap JSON: " + refmapPath);
        }

        int entryCount = countLeafEntries(root);
        RefmapResolver resolver = new RefmapResolver(root, mappingTable, entryCount);

        // Walk and rewrite the "mappings" block
        JsonObject mappings = root.getAsJsonObject("mappings");
        if (mappings != null) {
            resolver.walkMappings(mappings);
        }

        // Also walk "data" block if present (some refmap formats)
        JsonObject data = root.getAsJsonObject("data");
        if (data != null) {
            resolver.walkMappings(data);
        }

        return resolver;
    }

    /**
     * Write the corrected refmap JSON to a file.
     *
     * @param outputDir directory to write into (created if necessary)
     * @param pluginId  used for the filename: {@code {pluginId}.refmap.json}
     * @return the path to the written file
     * @throws IOException if writing fails
     */
    public Path writeTo(Path outputDir, String pluginId) throws IOException {
        Files.createDirectories(outputDir);
        Path outputPath = outputDir.resolve(pluginId + ".refmap.json");

        try (Writer writer = Files.newBufferedWriter(outputPath, StandardCharsets.UTF_8)) {
            GSON.toJson(root, writer);
        }

        LOGGER.info("[ZCSLIB/Mixin] Refmap written ({} rewritten / {} total): {}",
                rewrittenCount, originalEntryCount, outputPath);
        return outputPath;
    }

    /** @return number of entries rewritten in this refmap */
    public int rewrittenCount() {
        return rewrittenCount;
    }

    /** @return total leaf entries in the original refmap */
    public int originalEntryCount() {
        return originalEntryCount;
    }

    // ── Internal: walk & rewrite ───────────────────────────

    /**
     * Recursively walk the mappings object, rewriting string values
     * that match the member-reference pattern.
     */
    private void walkMappings(JsonObject node) {
        for (Map.Entry<String, JsonElement> entry : node.entrySet()) {
            JsonElement value = entry.getValue();
            if (value.isJsonObject()) {
                walkMappings(value.getAsJsonObject());
            } else if (value.isJsonPrimitive() && value.getAsJsonPrimitive().isString()) {
                String original = value.getAsString();
                String rewritten = rewriteMemberRef(original);
                if (!rewritten.equals(original)) {
                    entry.setValue(new com.google.gson.JsonPrimitive(rewritten));
                }
            }
        }
    }

    /**
     * Attempt to rewrite a single member-reference string.
     * Returns the original string unchanged if no rewrite is possible.
     */
    private String rewriteMemberRef(String ref) {
        Matcher matcher = MEMBER_REF_PATTERN.matcher(ref);
        if (!matcher.matches()) {
            return ref; // Not a member reference — leave untouched
        }

        String className = matcher.group(1);
        String memberName = matcher.group(2);
        String descriptorSuffix = matcher.group(3);

        // Determine if this is a method or field reference
        boolean isMethod = descriptorSuffix.startsWith("(");

        // Strategy: try Mojang→obf lookup first (memberName might be Mojang name)
        if (isMethod) {
            // memberName could be a Mojang method name like "split" or obf like "m_41620"
            // descriptorSuffix is the descriptor e.g. "(I)Lnet/minecraft/world/item/ItemStack;"
            String mojangDesc = memberName + " " + descriptorSuffix;
            Optional<String> currentObf = mappingTable.getMethodObf(className, mojangDesc);
            if (currentObf.isPresent() && !currentObf.get().equals(memberName)) {
                rewrittenCount++;
                LOGGER.debug("[ZCSLIB/Mixin] Rewrote method ref: {}.{} → {}",
                        className, memberName, currentObf.get());
                return "L" + className + ";" + currentObf.get() + descriptorSuffix;
            }
        } else {
            // Field: descriptor suffix is ":type"
            Optional<String> currentObf = mappingTable.getFieldObf(className, memberName);
            if (currentObf.isPresent() && !currentObf.get().equals(memberName)) {
                rewrittenCount++;
                LOGGER.debug("[ZCSLIB/Mixin] Rewrote field ref: {}.{} → {}",
                        className, memberName, currentObf.get());
                return "L" + className + ";" + currentObf.get() + descriptorSuffix;
            }
        }

        // If the member name looks like an obf name (m_xxx / f_xxx),
        // try reverse lookup: obf → Mojang → current obf
        if (looksLikeObfName(memberName)) {
            if (isMethod) {
                Optional<String> mojangDesc = mappingTable.getMethodMojang(className, memberName);
                if (mojangDesc.isPresent()) {
                    Optional<String> currentObf = mappingTable.getMethodObf(className, mojangDesc.get());
                    if (currentObf.isPresent() && !currentObf.get().equals(memberName)) {
                        rewrittenCount++;
                        LOGGER.debug("[ZCSLIB/Mixin] Rewrote method ref (reverse): {}.{} → {}",
                                className, memberName, currentObf.get());
                        return "L" + className + ";" + currentObf.get() + descriptorSuffix;
                    }
                }
            } else {
                Optional<String> mojangField = mappingTable.getFieldMojang(className, memberName);
                if (mojangField.isPresent()) {
                    Optional<String> currentObf = mappingTable.getFieldObf(className, mojangField.get());
                    if (currentObf.isPresent() && !currentObf.get().equals(memberName)) {
                        rewrittenCount++;
                        LOGGER.debug("[ZCSLIB/Mixin] Rewrote field ref (reverse): {}.{} → {}",
                                className, memberName, currentObf.get());
                        return "L" + className + ";" + currentObf.get() + descriptorSuffix;
                    }
                }
            }
        }

        // Check if the class itself has been renamed (obfuscation mapping)
        Optional<String> classObf = mappingTable.getClassObf(className);
        if (classObf.isPresent() && !classObf.get().equals(className)) {
            rewrittenCount++;
            LOGGER.debug("[ZCSLIB/Mixin] Rewrote class ref: {} → {}", className, classObf.get());
            return "L" + classObf.get() + ";" + memberName + descriptorSuffix;
        }

        // If not an obf mapping, try cross-version API rename
        // (e.g. 26.1: ResourceLocation → Identifier — not obfuscation, just a rename)
        if (classObf.isEmpty()) {
            Optional<String> classRename = mappingTable.getClassRename(className);
            if (classRename.isPresent() && !classRename.get().equals(className)) {
                rewrittenCount++;
                LOGGER.debug("[ZCSLIB/Mixin] Rewrote class ref (rename): {} → {}",
                        className, classRename.get());
                return "L" + classRename.get() + ";" + memberName + descriptorSuffix;
            }
        }

        // If class is not in the mapping table or rename table at all, warn once per class
        if (classObf.isEmpty()
                && mappingTable.getClassRename(className).isEmpty()
                && unmappedClasses.add(className)) {
            LOGGER.warn("[ZCSLIB/Mixin] Class '{}' not found in mapping table. "
                    + "Refmap entry '{}' kept unchanged.", className, ref);
        }

        return ref;
    }

    /** Heuristic: obfuscated names from Minecraft follow {@code m_<num>} or {@code f_<num>}. */
    private static boolean looksLikeObfName(String name) {
        return (name.startsWith("m_") || name.startsWith("f_"))
                && name.length() > 2
                && Character.isDigit(name.charAt(2));
    }

    /** Count the number of leaf string values in a JSON tree for logging. */
    private static int countLeafEntries(JsonObject node) {
        int count = 0;
        for (var entry : node.entrySet()) {
            JsonElement value = entry.getValue();
            if (value.isJsonObject()) {
                count += countLeafEntries(value.getAsJsonObject());
            } else if (value.isJsonPrimitive() && value.getAsJsonPrimitive().isString()) {
                count++;
            }
        }
        return count;
    }
}
